pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Gradle Static Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh './gradlew clean sonarqube'
                }
            }
        }
    }
}
